spring:
  profiles.active: git
  application:
    name: newv-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/bleusoir/newv-cloud-config.git

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
